# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-02 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='role',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
